### ISSUE TITLE
[Feature Request] Preview Selected Item (CRTL+SPACE) -> Keyboard Navigation Support

### ISSUE THREAD

**Issue by FelipeRearden** [qawatake/obsidian-core-search-assistant-plugin#1]
Hello @qawatake !!!!!!!!

First of all I just wanna say thank very much for creating this plugin !!!!!!

As a keyboard lover, I have been dreaming for a keyboard navigation in the search panel for a long time !!!!! 🙏 

This FR is related to the behavior inside the Preview View after hitting CRTL+SPACE

## MY FR

Would be amazing if after hitting CRTL+SPACE the user could continue to use the keyboard arrows to navigate in the preview note. 

In the latest version, I have to click with the mouse inside the modal to be able to start to use the keyboard arrows to navigate 

--- 

Let me know what you think :)

Have a great day !

**Comment by qawatake** [comment]
will be implemented in #7

**Comment by FelipeRearden** [comment]
> will be implemented in #7 

Hello @qawatake !!!!

Working perfect on version 2.0.0 on Obsidian 0.13.19

Thank you very much !!!!!
