### ISSUE TITLE
[BUG] focus failed for a large note

### ISSUE THREAD

**Issue by qawatake** [qawatake/obsidian-core-search-assistant-plugin#19]
Hello @qawatake !!!!!

I was testing the TAB command since yesterday and I think I found a BUG. 
- The TAB command is not able to navigate between ALL of the Matches
- The TAB command is not able to navigate to ANYONE of the matches.

Version 0.3.2
Obsidian 0.13.19
Legacy Mode is OFF 

Here is what I found today ....

Example 
My note name is Apple.md
my note has 3000 lines
the term I want to search is the word MacOS
I have 3 matches for this search 
The first match is located in line 2000
The second match is located in line 2500
The third is located in line 2999

Bug -> When the matches of a note are not visible when opening the MANUAL VIEW (they are in the end of the note) , the TAB command is not working.  
- If you have 2 in the beginning and 5 in the end. Tab will navigate only between these first two matches in loop
- looks like that the navigation is limited to a certain amount of lines.

I think I found more bugs but I didnt find the pattern yet. I gonna keep testing to see if I found something more :)

_Originally posted by @FelipeRearden in https://github.com/qawatake/obsidian-core-search-assistant-plugin/issues/6#issuecomment-1021456234_

**Comment by qawatake** [comment]
@FelipeRearden

I think I have fixed the problem.
Could you try it again?
https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.3.3

**Comment by FelipeRearden** [comment]
Hello @qawatake !!!!!

One word: PERFECT !!!!!!!!!!

It´s exactly what we expect, the navigation is fast and gets every match. 

Thank you very for your work! You are creating a legend plugin for Obsidian :)
