### ISSUE TITLE
[Feature Request] Preview Selected Item (CRTL+SPACE) -> Ability to Open File from the Modal

### ISSUE THREAD

**Issue by FelipeRearden** [qawatake/obsidian-core-search-assistant-plugin#2]
Hello @qawatake !!!!!!

This FR is related to the behavior inside the Preview View after hitting CRTL+SPACE

Would be amazing to be able to open the file (using the command CRTL+ENTER) while the user is located in the Preview View (CRTL+SPACE) 

After using the preview view, the user can exit (ESC) or open the note (CRTL+ENTER) to start working :)

---

Thanks for reading this :)

**Comment by qawatake** [comment]
implemented in #7

**Comment by FelipeRearden** [comment]
> implemented in #7 

Hello @qawatake !!!!

Working perfect on version 2.0.0 on Obsidian 0.13.19

Thank you very much !!!!!
