### ISSUE TITLE
Feature Request: During Search mode, the other sidebar should be collapsed

### ISSUE THREAD

**Issue by chrisgrieser** [qawatake/obsidian-core-search-assistant-plugin#20]
As you can see, I have my search pane on the right, and also the sidebar on the left. Without the plugin, having both sidebar tabs does not make a real difference. 

With the card view, however, it does make a difference, since the cards become quite narrow. The card view would benefit from having more space, so it would be useful if the sidebar that does not contain the search pane would become automatically hidden when in "search mode", and would restore to the previous state when leaving search mode.

![Screenshot 2022-01-28 02 20 37](https://user-images.githubusercontent.com/73286100/151470423-f2318f0c-e354-4922-b1f6-63e4ad6ecfae.png)

(PS: don't be confused about how the card view looks – I am styling the card view in my theme right now :) )

**Comment by qawatake** [comment]
@chrisgrieser 

I implemented your request at pre-release [0.4.0](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.4.0).
Could you try it?
To enable the feature, you have to set `Toggle sidebars automatically` on in the setting tab.

**Comment by chrisgrieser** [comment]
works like a charme. thanks a lot, this plugin is getting more and more useful 🤩
