### ISSUE TITLE
Bug: while the plugin is enabled, an additional (buggy) resize handle is added

### ISSUE THREAD

**Issue by chrisgrieser** [qawatake/obsidian-core-search-assistant-plugin#21]
https://user-images.githubusercontent.com/73286100/151623875-a4ff7db2-54d0-4328-92c7-43cdbcc8dc60.mov

**Comment by qawatake** [comment]
@chrisgrieser 

Thank you for reporting.
I made a pre-release [0.3.6](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.3.6).
Could you try it?

**Comment by chrisgrieser** [comment]
sure, but the release does not include anything than the source code though 😛

**Comment by qawatake** [comment]
@chrisgrieser 

Really?
I can see `main.js` in the assets of 0.3.7 even after signing out.
Could you see the pre-releasee again?

**Comment by chrisgrieser** [comment]
ah, the issue was that the link GitHub send me via mail was from the unedited version, not version 0.3.7
![Screenshot 2022-01-29 12 15 30](https://user-images.githubusercontent.com/73286100/151658877-0dcee601-1578-483a-93fb-0c2d8f9c42dc.png)


version 0.3.7 has the files. I'll update and report in a moment

**Comment by chrisgrieser** [comment]
can confirm, resize handle does not appear anymore with 0.3.7.

Thanks for the quick fix 🤗
