### ISSUE TITLE
[Bug] Preview opens unknown files with default application on Windows

### ISSUE THREAD

**Issue by generic-user** [qawatake/obsidian-core-search-assistant-plugin#22]
Version: 0.3.7
OS: Windows

When the preview gets generated for an unknown file type, it opens it with the default application.

Ea: xml, html, drawio files.

Thanks for the plugin, It's a beauty. 🎉

**Comment by qawatake** [comment]
@generic-user 

Could you share a screen recording of that problem?

**Comment by qawatake** [comment]
@generic-user 

Can I close this issue?

**Comment by qawatake** [comment]
@generic-user 

Thanks. I understand it. The problem occurs when you search with `file:` or `path:`.

I'll fix the bug in the next update.

**Comment by generic-user** [comment]
Hi I tested it, it seems fixed. Thanks!
