### ISSUE TITLE
Bug: When plugin is active, cannot switch to a different tab

### ISSUE THREAD

**Issue by chrisgrieser** [qawatake/obsidian-core-search-assistant-plugin#24]
https://user-images.githubusercontent.com/73286100/151958721-0f9cfefd-1d89-4a92-a9c8-1a089be95937.mov

**Comment by qawatake** [comment]
@chrisgrieser 

Thank you for reporting!
Could you try pre-release [0.4.1](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.4.1)?

**Comment by chrisgrieser** [comment]
thanks for the quick fix – works as intended
