### ISSUE TITLE
Don't show the card pane and plugin conflict

### ISSUE THREAD

**Issue by HuangAdam** [qawatake/obsidian-core-search-assistant-plugin#25]
No other plugins:
![Quicker_20220204_233701](https://user-images.githubusercontent.com/46439030/152557382-8f65eae2-8d69-4f6d-89b5-43ee0a846fdc.png)

Conflict with [Obsidian Tabs](https://github.com/gitobsidiantutorial/obsidian-tabs)
![Quicker_20220204_235300](https://user-images.githubusercontent.com/46439030/152559964-4f25e383-755c-4c2d-ad9a-98660eab11fa.png)

**Comment by qawatake** [comment]
@HuangAdam 

Thank you for your report.
However, I did not find any conflicts.
Please tell us more about your environment and the problem.

**Comment by HuangAdam** [comment]
> @HuangAdam
> 
> Thank you for your report. However, I did not find any conflicts. Please tell us more about your environment and the problem.

Sorry for the wrong word.
Maybe "overwritten" will be more accurate.
My file:
![Quicker_20220205_210354](https://user-images.githubusercontent.com/46439030/152643279-9239f020-5a5b-4d3a-b13a-bd7f9b31ff04.png)
With tabs plugin:
![Quicker_20220205_210340](https://user-images.githubusercontent.com/46439030/152643286-b9835baa-5809-4bcf-bafa-dc53286620a2.png)
Without it:
![Quicker_20220205_210345](https://user-images.githubusercontent.com/46439030/152643310-7d26d344-72a6-45bf-8abc-d557420cf9c9.png)
And Why do it only show the text instead of card?

**Comment by HuangAdam** [comment]
I had tried to create new vault or switch live preview. It is same.
Current version: 0.13.23
Plugin version: 0.4.1
System: Windows10 21H2

**Comment by qawatake** [comment]
@HuangAdam 

I have some questions.
- Do you use any custom snippet?
- Do you use any custom theme?
- Do you disable all plugins other than Obsidian tabs and Core Search Assistant?

**Comment by qawatake** [comment]
@HuangAdam 

Sorry, you don't have to answer the questions above.
Instead, please share the output from command `Show debug info`.

**Comment by HuangAdam** [comment]
@qawatake 

OK, I find the reason, that I download the wrong file.
Thanks for your reply, and sorry to wasted your time.
