### ISSUE TITLE
FR: Hotkey for jumping to the next set of cards

### ISSUE THREAD

**Issue by HEmile** [qawatake/obsidian-core-search-assistant-plugin#27]
Hi, really liking the cards view! Much better overview of the search results than vanilla Obsidian provides. However, I'm not seeing a hotkey to jump to the next set of cards. There is a hotkey to move to the next selection with ctrl+n, but with the 3x3 cards layout, this requires 9 clicks to get there. Can there be a hotkey to create the next set of cards?

**Comment by qawatake** [comment]
@HEmile

**Comment by qawatake** [comment]
@HEmile 

Thank you for your request!
I will implement it soon.
I'm thinking of `Ctrl + ←/→` as hotkeys.

**Comment by qawatake** [comment]
@HEmile 

I implemented page moves by hotkeys in pre-release [0.5.0](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.5.0).
I adopt `Ctrl + ]` and `Ctrl + [`  as hotkeys.
I hope you will try this feature.
