### ISSUE TITLE
Move through the search result with ctrl+j/k

### ISSUE THREAD

**Issue by tonygrr** [qawatake/obsidian-core-search-assistant-plugin#29]
Hi! Thank you very much for your work. Your plugin makes it a lot easier to work without using the mouse. I would like to suggest adding a toggle by search results via the ctrl+j/k keys for vim mod users. That would be incredibly convenient.

**Comment by qawatake** [comment]
@tonygrr 

Thank you for your request!

In release [0.6.0](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.6.0), you can customize hotkeys.
Could you manually install and try it?
