### ISSUE TITLE
[Feature Request] Preview Selected Item (CRTL+SPACE) -> CSS to achieve Full Screen 

### ISSUE THREAD

**Issue by FelipeRearden** [qawatake/obsidian-core-search-assistant-plugin#3]
Hello @qawatake !!!!!!!!

This FR is related to the behavior inside the Preview View after hitting CRTL+SPACE

Would you mind changing the CSS from the modal of the preview view to an specific modal ?

I'm asking you this because I want to create a snippet for this specific modal for a Full Screen mode !!!!!!

The way that we have today, if I change the CSS, it will change other modals in Obsidian :(

---

Thanks for reading this ! 

Have a great day!!!!!!!

**Comment by qawatake** [comment]
Is it enough for you to add class like `core-search-assistant_preview-modal-container` to the modal container element (= `div.modal-container`)?

**Comment by FelipeRearden** [comment]
Hello @qawatake !!!!

Before answer your question. Let me share with you two things:

1- I’m not an CSS expert. I just go by try and error asking for questions to the developers and on Discord

2- I did the same FR for another plugin and the developer create and specific modal. Take a look above
- Before the new modal, this plugin used the same modal as the one that you are using now :)

This is the link of my FR. Maybe with the information in the FR something clicks on your mind (since I don’t know the technical terms of what I’m asking 

https://github.com/joethei/obsidian-rss/issues/51


> Is it enough for you to add class like `core-search-assistant_preview-modal-container` to the modal container element (= `div.modal-container`)?

I don’t know. I am gonna wait for your reply from this answer to see if we are on the same page :)

If not I gonna ask for one of our CSS wizards Chris help :)

Let keep talking :)

Have a great day!

**Comment by qawatake** [comment]
> Is it enough for you to add class like `core-search-assistant_preview-modal-container` to the modal container element (= `div.modal-container`)?

I will do this in the next update.
Then you will get the desired result by something like:
```css
.core-search-assistant_preview-modal-container .modal {
  width: 100%;
  height: 100%;
  max-width: none;
}
```

[![Image from Gyazo](https://i.gyazo.com/6eb7f3b97b8625669480dbce0520be1c.png)](https://gyazo.com/6eb7f3b97b8625669480dbce0520be1c)

**Comment by FelipeRearden** [comment]
Thank you very for making this 😃 !!! @qawatake !!!

**Comment by FelipeRearden** [comment]
Hello @qawatake !!!!!!

Working prefect on version 0.2.1 on Obsidian 0.13.19

Thank you very much. This is a huge step for my workflow !!!!!!
