### ISSUE TITLE
[Issue] Cannot click search results in sidebar

### ISSUE THREAD

**Issue by ryadaj** [qawatake/obsidian-core-search-assistant-plugin#31]
Hi there,

Amazing plugin, I love it.

Sometimes selecting results in sidebar is desirable, but when plugin is enabled I can only click the "cards"

Also, cannot use other hotkeys in search menu, such as `command` + `O` for open or `command` + `,` for settings

Thanks!
Ryan

https://user-images.githubusercontent.com/82765301/153737932-aa5bf915-ee0d-449e-8e38-59bc87fd6cfe.mov

**Comment by qawatake** [comment]
@ryadaj 

Thank you for reporting!

> Sometimes selecting results in sidebar is desirable, but when plugin is enabled I can only click the "cards"

Yes, it is a bug. I'll fix it in the near future.

> Also, cannot use other hotkeys in search menu, such as command + O for open or command + , for settings.

This is an expected behavior to avoid hotkey collision. If you want to use other hotkeys, you have to exit the **search mode**.
