### ISSUE TITLE
[Feature Request] Use Mac keys for shortcuts

### ISSUE THREAD

**Issue by Signynt** [qawatake/obsidian-core-search-assistant-plugin#34]
There should be an option to use the typical Mac keys for the shortcuts, like `Ctrl + Enter`, mainly using Command (`Mod`) instead of Ctrl.

**Comment by qawatake** [comment]
@tonygrr 

Thank you for your request!

In release [0.6.0](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.6.0), you can customize hotkeys.
Could you manually install and try it?
