### ISSUE TITLE
[BUG?]Rerender while search excalidraw file.

### ISSUE THREAD

**Issue by Quorafind** [qawatake/obsidian-core-search-assistant-plugin#35]
https://user-images.githubusercontent.com/13215013/154003888-a87441aa-8abc-4190-9f90-fa7997b5e8d6.mp4

Tons of errors, don't know if this caused by this plugin or excalidraw plugin.

![image](https://user-images.githubusercontent.com/13215013/154003753-d1f029e8-8756-40b2-99ed-06b28befc896.png)

**Comment by qawatake** [comment]
@Quorafind 

Thank you for reporting!
In the next update, I will support excalidraw.

**Comment by qawatake** [comment]
@Quorafind 

I think I have fixed the bug in pre-release [0.6.1](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.6.1).
Could you try it?

**Comment by Quorafind** [comment]
Yes, works great.
