### ISSUE TITLE
[Feature Request] New Command Open the select item in a NEW PANEL

### ISSUE THREAD

**Issue by FelipeRearden** [qawatake/obsidian-core-search-assistant-plugin#4]
Hello @qawatake !!!!!

I just wanna suggest the addition of a new command to Open the select item in a NEW PANEL -> CRTL+ SHIFT+ ENTER 

Key | Action
-- | --
Ctrl + Enter | Open the selected item.
Crtl+Shift +Enter | Open the selected item in a new panel

Have a great day!!!!1

**Comment by kabo1234** [comment]
+1

**Comment by qawatake** [comment]
implemented in #7

**Comment by FelipeRearden** [comment]
> implemented in #7 

Hello @qawatake !!!!

Working perfect on version 2.0.0 on Obsidian 0.13.19

Thank you very much !!!!!
