### ISSUE TITLE
[Feature Request] Highlight searched word in Card View

### ISSUE THREAD

**Issue by Signynt** [qawatake/obsidian-core-search-assistant-plugin#41]
Currently I still have to rely on the default search results of Obsidian to find the result that I'm looking for, since the card view will show the top of the note, and even if the search word is visible, it's hard to quickly find it without it being hightlighted.

**Comment by qawatake** [comment]
@Signynt 

Thank you for your request! But I'm not positive about implementing that. Please see the reason in #6.
