### ISSUE TITLE
[Bug?] hotkey does not work after search

### ISSUE THREAD

**Issue by wzajchow** [qawatake/obsidian-core-search-assistant-plugin#44]
By clicking a card in a card view I would like to open this note and close the search view. Currently, it opens the note in the background, but the search view remains on top of it.

**Comment by qawatake** [comment]
@wzajchow 

That may be a bug.
Could you retry after disabling all the other plugins?
And please share
1. screen recording,
2. debug info. (You can get it by executing  `Show debug info` command.)

**Comment by wzajchow** [comment]
[Recording](https://streamable.com/s16856)

```
SYSTEM INFO:
	Obsidian version: v0.13.23
	Installer version: v0.12.19
	Operating system: Windows 10 Pro 10.0.19044
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Atom
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 27
	Plugins enabled: 1
		1: Core Search Assistant

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
```
Clicking on the search results doesn't work either if the search preview is enabled. 
I have also noticed that after I do a search, global shortcuts for command palette and quick switcher will stop work. 


This may be a specific bug for my environment. I am trying to narrow down the issue but no success.

**Comment by qawatake** [comment]
@wzajchow 

Thanks!
Hmm, I could not reproduce the bug with Atom theme.
Could you check and share the output of the console (by pressing `Ctrl + Shift + I`)?

And if possible, could you retry in a newly created vault?

**Comment by wzajchow** [comment]
I made a few tests and problem with global shortcut Ctrl+P and Ctrl+O appears only after I enable Core Search Assistant plugin.

**Comment by wzajchow** [comment]
To reproduce the issue.
1. Open Obsidian
2. Try ctrl+P/ctrl+O - it works
3. Try search
4. Again ctrl+P/ctrl+O - it works
5. Enable Core Serach plugin
6. ctrl+P/ctrl+O - it works
7. **Try Search - clicking on notes doesn't work**
8. **ctrl+P/ctrl+O - it doesn't work anymore** 

[Video](https://streamable.com/7eva6p)

**Comment by qawatake** [comment]
@wzajchow 
Hmm, I'm sorry, but I haven't found a way to reproduce the bug.
Could you try one of the followings?
- [Release 0.7.0](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.7.0)
  - You must manually install it.
- Enable option *Render cards manually*.

**Comment by wzajchow** [comment]
With 0.7.0 installed and _Render cards manually_ everything works perfect. No issues with hotkeys and clicking on cards open the note. 
I will test with other plugins enabled.

**Comment by wzajchow** [comment]
Works with other plugins enabled too. 
As soon as I disable _Render cards manually_ clicking and global shortcut won't work anymore (Obsidian restart in necessary).

**Comment by qawatake** [comment]
@wzajchow 

Thanks.
What happens if I enable *Render cards manually* in the latest release?

**Comment by scpedicini** [comment]
I'm aware this issue is closed, but core-search also has a tendency to break all my global hotkeys (especially if I use the search which shows the cards, but then escape or don't select one of them).

Only a full restart of Obsidian fixes it.

**Comment by MariosGkMeng** [comment]
> wzajchow

Today I also had issues with my hotkeys (none would work).

Somehow it got fixed by disabling the community plugins, closing Obsidian and re-opening it 🤷‍♂️
