### ISSUE TITLE
index pdfs as well?

### ISSUE THREAD

**Issue by eleanorkonik** [qawatake/obsidian-core-search-assistant-plugin#47]
Is it remotely possible for this plugin to potentially also show PDFs in the search results? I often find myself searching my vault for things ("hrm, what do I already have in here about eggs?") before I go and do broader research, but I keep forgetting to check my PDFs in an external app because I'm so used to relying on Obsidian search to resurface my information. If I were a mac user maybe I'd be in the habit of using devonthink, but I'm not, so I keep forgetting to launch foxit reader and readwise to get the "full archive."

This would allow me to get so much more use out of Obsidian search, but I don't know how hard it would be.

**Comment by qawatake** [comment]
Hi, @eleanorkonik.

You would like to search PDFs outside the vault, right?
If it is, I'm afraid that I cannot add the feature to this plugin.
This plugin is just an assistant, so it does not extend the search feature itself.

If you create a markdown file that has a link to an external PDF, you can find the markdown file by searching and then the PDF through it. But it would not be what you want.

**Comment by eleanorkonik** [comment]
My PDFs are in the vault, if that helps? I'm not trying to search anything that's outside the vault, I'm just trying to search different file extensions inside the vault. Similar to how the csv and cooklang plugins let you view an otherwise unsupported file type in the obsidian interface.

But I totally understand if it's beyond the scope of this plug-in, I was just trying to get a sense of how hard it would be and you're the person who has done the most with the search functionality in obsidian.

**Comment by qawatake** [comment]
@eleanorkonik 

> My PDFs are in the vault, if that helps? I'm not trying to search anything that's outside the vault, I'm just trying to search different file extensions inside the vault. 

Oh, sorry for my misunderstanding. As you know, you can search different file extensions by querying like `file:.pdf` or `path:.csv`.
The weak point is that you can search by only file names. Searching by file contents is beyond the scope of this plugin 😢
(@nothingislost may be closer to the feature. He dives into the private search API of Obsidian in his [Query Control plugin](https://github.com/nothingislost/obsidian-query-control/tree/master).)

Displaying different file extensions will be possible. Indeed, I do this for Kanban and Excalidraw plugins. But it needs steps:
1. Install a plugin that provides appropriate views. (e.g., csv or cooklang plugin)
2. Add codes that register the plugin to Core Search Assistant.
    - I need an instance that implements interface https://github.com/qawatake/obsidian-core-search-assistant-plugin/blob/9c6ab42a7d3aafdbeec172eb4eec00e6d3a73c3e/src/interfaces/ViewGenerator.ts#L134-L142
    - For example, I wrote codes for Kanban [here](https://github.com/qawatake/obsidian-core-search-assistant-plugin/blob/9c6ab42a7d3aafdbeec172eb4eec00e6d3a73c3e/src/interfaces/viewGeneratorExtensions/Kanban.ts).

**Comment by eleanorkonik** [comment]
Aha! Thank you, that is precisely the lead I needed, thank you so much!
