### ISSUE TITLE
Bug: Plugin does not seem to work at all

### ISSUE THREAD

**Issue by chrisgrieser** [qawatake/obsidian-core-search-assistant-plugin#5]
I installed the plugin via BRAT, and it seems I can't get the plugin to work.

Reinstalling the plugin, restarting Obsidian, disabling/re-enabling the plugin or disabling all other plugins does not make a difference. I am on macOS 12.0.1, if that matters.

I opened the console and when typing things into the search bar, nothing is reported there.

**Comment by qawatake** [comment]
@chrisgrieser 
Any other version did not work?
Any other features like single view or keyboard interface did not work?

**Comment by qawatake** [comment]
By the way, it worked fine on macOS 11.6.2 and Obsidian with current/installer version 0.13.19.

**Comment by chrisgrieser** [comment]
> Any other version did not work?
what other version? 

> Any other features like single view or keyboard interface did not work?

as far as I can tell, not a single feature works.

Also, there are also other people on Discord reporting that the plugin does not seem to work for them: https://discord.com/channels/686053708261228577/707816848615407697/934082673033510962

**Comment by FelipeRearden** [comment]
@qawatake and @chrisgrieser 

Just to give my feedback . I did a manual install on obsidian 0.13.19 on version 0.1.4

100% working here.

**Comment by qawatake** [comment]
@chrisgrieser 
> what other version?

What about [0.0.1](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.0.1)?
It provides features other than card view (but hotkeys are a bit different).
https://github.com/qawatake/obsidian-core-search-assistant-plugin/tree/4d5edfb7a5a478f219dcdb57c2bfd437e8f5d211

**Comment by qawatake** [comment]
I would like to gather information on which platforms it does not work on.

**Comment by qawatake** [comment]
@FelipeRearden 
What is your device?

**Comment by chrisgrieser** [comment]
> What about 0.0.1?
Installed it, still nothing showing up.

```
Obsidian 0.13.19

**Comment by chrisgrieser** [comment]
disabled all plugins, used 0.0.1, still nothing.

**Comment by FelipeRearden** [comment]
> @FelipeRearden 
> 
> What is your device?

My environment for testing plugins on beta is: 

Windows 7 
Obsidian 0.13.19
Plug-in version 0.1.4

**Comment by qawatake** [comment]
@FelipeRearden 

Thank you!

**Comment by qawatake** [comment]
@chrisgrieser 

Hmm.
Ok, I'll update my mac to Monterey and try to investigate the problem on this weekend.

**Comment by FelipeRearden** [comment]
> Ok, I'll update my mac to Monterey and try to investigate the problem on this weekend.

I wish you 🍀 @qawatake !!!!!

**Comment by chrisgrieser** [comment]
btw, it does not seem to be the Mac version per se.

I installed the plugin in the help vault, and it works there. Tried again in my actual vault, it doesn't work there anymore. Even with all other plugins disabled and css disabled. 🤔

**Comment by qawatake** [comment]
What about the newly created folder?

**Comment by chrisgrieser** [comment]
what newly created folder?

**Comment by qawatake** [comment]
Sorry, what about a newly created **vault**?

**Comment by chrisgrieser** [comment]
a newly created vault works, too.

**Comment by qawatake** [comment]
> btw, it does not seem to be the Mac version per se.

I upgrade my mac to Monterey, and the plugin still works on it.
I'd like to have a minimal reproducible environment.

**Comment by kabo1234** [comment]
Just to report it worked fine for me! But I had to hit ‘enter’ before the card view showed and that had me stumped at first. I also restarted Obsidian, just to make sure, and it worked.

**Comment by chrisgrieser** [comment]
> I upgrade my mac to Monterey, and the plugin still works on it.
I'd like to have a minimal reproducible environment.

Yeah being a dev myself, I know. However, I cannot seem to find out what the issue is. I uninstalled, installed the new 0.2.1 release, still does not work in my normal vault. deactivated all plugins except this one, still doe snot work. :(

**Comment by FelipeRearden** [comment]
@chrisgrieser would you mind sharing your Core plugins window ?

I wanna compare to my settings to see if I find some to help @qawatake !

I hope you can use this plug-in! I know you will bring fantastic ideas and FR :)

**Comment by chrisgrieser** [comment]
@FelipeRearden That's very nice of you 💙

Yeah, so I haven't changed any of the default settings. But here they are: 
<img width="1093" alt="Screenshot 2022-01-23 22 09 57" src="https://user-images.githubusercontent.com/73286100/150698085-e2788b90-2e03-4f58-af91-1b0370bf3242.png">

**Comment by FelipeRearden** [comment]
These are mine

![0](https://user-images.githubusercontent.com/85180696/150698605-aac23fa1-ef2b-4112-adfe-71aba2f4202b.png)

@qawatake might be something related to Core Plugins enable/disable? Im sharing my Core plugins list  

![1](https://user-images.githubusercontent.com/85180696/150698648-0f4728e5-48bf-42b9-ba47-300b4c374da8.png)
![2](https://user-images.githubusercontent.com/85180696/150698649-f60ee8f8-5c39-4dea-8db2-4d066753664f.png)
![3](https://user-images.githubusercontent.com/85180696/150698650-8eda82d2-9796-4bee-b670-c40b224c00d1.png)

### One more thing

@chrisgrieser in my case I always start using the plugin calling the command `Search: Search in All Files`

After hitting this command the screen gets "outlined" and then I use the Arrows UP and DOWN to navigate 

Sometimes I have to hit  `Search: Search in All Files` to get things going

---

I here sending my positive energy !!!!!! :pray:

**Comment by chrisgrieser** [comment]
hmm, I tried enabling all core plugins as well, no luck. Guess we will have to see what @qawatake suggests for debugging. 😔

**Comment by FelipeRearden** [comment]
> hmm, I tried enabling all core plugins as well, no luck. Guess we will have to see what @qawatake suggests for debugging. 😔 

Yeah ! Sorry for not helping :)

I don't have anymore ideas to see any between our vaults :)

Let's wait for @qawatake !!!

Have a great day!!!!!!

**Comment by qawatake** [comment]
@FelipeRearden 
Thank you for helping!

**Comment by qawatake** [comment]
@chrisgrieser 

I made a branch for debugging (https://github.com/qawatake/obsidian-core-search-assistant-plugin/tree/debug-%235) with `main.js` and `styles.css`.
It contains several `console.log` for print debugging.

Could you install `main.js` and `styles.css` manually and report what is displayed?
If every components are successfully loaded, the following is displayed at startup:
[![Image from Gyazo](https://i.gyazo.com/3d296385dd0ec15b96b21a5b0e8b448d.png)](https://gyazo.com/3d296385dd0ec15b96b21a5b0e8b448d)

And please try to navigate by `↓` or `↑`, and submit by `Enter`
[![Image from Gyazo](https://i.gyazo.com/3a1460176140f58bc4540b990d1085a3.png)](https://gyazo.com/3a1460176140f58bc4540b990d1085a3)
[![Image from Gyazo](https://i.gyazo.com/718e82531071c541b7d8b3c46f8b87fd.png)](https://gyazo.com/718e82531071c541b7d8b3c46f8b87fd)

**Comment by chrisgrieser** [comment]
Sure thing, installed them and this is the result. The components are loaded successfully when on Obsidian launch, but focussing the search pane input doesn't do anything
https://user-images.githubusercontent.com/73286100/150768708-d601033f-febf-4f1c-b52b-92bdd3c7e3f1.mov

**Comment by qawatake** [comment]
@chrisgrieser 

Thank you for sharing!
Maybe the cause is that you put the search panel to the left panel.
Could you put it to the right?

**Comment by chrisgrieser** [comment]
lol, you are right. putting the panel to the left and it works. put it to the right, and it stops working.
https://user-images.githubusercontent.com/73286100/150773164-729bc5ce-5bb2-4457-8b5c-c4cdda1e6842.mov

**Comment by qawatake** [comment]
@chrisgrieser 

Good!
In the next update, I will support the case where the search panel is on the right side.
Until then, please keep the search panel on the left.

**Comment by chrisgrieser** [comment]
got, it, thanks!

**Comment by FelipeRearden** [comment]
THIS IS GREAT @qawatake AND @chrisgrieser !!!!!!!!!!!!!!!!!
