### ISSUE TITLE
Transparent Overlay breaks hotkeys (Demo)

### ISSUE THREAD

**Issue by scpedicini** [qawatake/obsidian-core-search-assistant-plugin#51]
I really want to use this plugin, but it seems to very consistently break all global hotkeys for me in various situations. I've figured out the most consistent way to repro the issue, and attached an MP4 (with audio) demonstrating the problem. 

https://user-images.githubusercontent.com/2040540/166115607-aef4ef43-88ef-4651-af97-4d206205d0f9.mp4

Details:
Tested with Obsidian v0.14.6 and no additional plugins (except Core Search Assistant)

**Comment by qawatake** [comment]
@scpedicini 

Thank you for reporting a bug!

I have created a branch for the patch.
Could you install `main.js` manually from the [path branch](https://github.com/qawatake/obsidian-core-search-assistant-plugin/tree/patch-%2351) and replace the original `.obsidian/plugins/obsidian-core-search-assistant-plugin/main.js` by it?

**Comment by scpedicini** [comment]
After about 30 minutes of trying to get the plugin to break the shortcuts, this seems to have fixed the issue. Thanks for the patch!
