### ISSUE TITLE
Core Search Assistant doesn't work after I upgraded to Obsidian 15.2

### ISSUE THREAD

**Issue by Randy-Astle** [qawatake/obsidian-core-search-assistant-plugin#55]
I've been using card view but have tried other options. In all cases, Core Search Assistant doesn't seem to be working after I upgraded to Obsidian 15.2.

It behaves just like the built-in search: the search list is displayed in the left panel and can be filtered by entering a term, but none of the preview modes are working (except perhaps None :-D).

Also the shortcut keys for switching to the next and previous items in the results list don't work.

**Comment by scpedicini** [comment]
Confirmed - this seems to be broken in future versions including v0.15.6 as well.

**Comment by qawatake** [comment]
Sorry for the late reply. The plugin now supports Obsidian v0.15.6.
