### ISSUE TITLE
Not updated for Obsidian 16+

### ISSUE THREAD

**Issue by Randy-Astle** [qawatake/obsidian-core-search-assistant-plugin#59]
I liked this community plugin, but it really needs to be updated for Obsidian 16.x. :-(

The cards view now shows what are essentially thumbnail views. And, with all the changes in Obsidian, there are probably other issues as well.

For me, it is now essentially unusable -- i.e. no better than Obsidian's search.

**Comment by qawatake** [comment]
https://github.com/qawatake/obsidian-core-search-assistant-plugin/pull/63
