### ISSUE TITLE
[feature request] show search term in context

### ISSUE THREAD

**Issue by kabo1234** [qawatake/obsidian-core-search-assistant-plugin#6]
Hi there,

loving the card view! Would it be possible to show the ‘block’ (paragraph) in which the search term is found? At the moment the card shows the file and not where in the file the search term is. And I often have multiple occurrences of the search term (eg a hashtag) in the same page, so it would be very helpful to see the context. 

Thanks!

**Comment by FelipeRearden** [comment]
+1

**Comment by qawatake** [comment]
@kabo1234 
Thank you for a request!

I agree with you partially, but I'm not positive about implementing that for the following reasons.

First, I think the left panel with "*show more context*" option  is enough.
The left panel and the card view have different roles:
- The left panel provides information about where matches are.
- The card view provides an overview of matched file.

Second, I have no idea what to display in a card when the content of a selected item is very large and it has multiple occurrences of the search term.

But I believe that previews should provide information about matches.
For example, I'm considering that matches are highlighted in the preview modal (manual preview).

**Comment by FelipeRearden** [comment]
> For example, I'm considering that matches are highlighted in the preview modal (manual preview).

You read my mind @qawatake . That is exactly what I was gonna ask you !!!!!

Manual preview is getting stronger 🦾 !!!!

**Comment by kabo1234** [comment]
> @kabo1234 Thank you for a request!
> 
> I agree with you partially, but I'm not positive about implementing that for the following reasons.
> 
> First, I think the left panel with "_show more context_" option is enough. The left panel and the card view have different roles:
> 
> * The left panel provides information about where matches are.
> * The card view provides an overview of matched file.
> 
> Second, I have no idea what to display in a card when the content of a selected item is very large and it has multiple occurrences of the search term.
> 
> But I believe that previews should provide information about matches. For example, I'm considering that matches are highlighted in the preview modal (manual preview).

Ah, yes, I see the problem. I find the side panel view close to unusable with lots of results and was looking for a more visually appealing way to 'see' the results -> card view! :)

for multiple occurrences in the one document (exactly my use case):
- make the cards scrollable and start with the first occurrence 
- show multiple cards per page, each with a single occurrence (this could get overwhelming fast if the search query isn't precise...)

neither might be possible, I wouldn't know :) 

I'll check out the manual preview! I've only looked at the card view so far.

**Comment by qawatake** [comment]
@kabo1234 

I implemented a new feature related to your request.
Now you can easily find matches in the manual view by hitting `Tab`. Please try it.
I believe the feature is enough for you

**Comment by FelipeRearden** [comment]
> Now you can easily find matches in the manual view by hitting `Tab`. Please try it.

And `SHIFT+TAB` to previous match :)

**Comment by kabo1234** [comment]
This sounds good, but I can't get it to work at all...let me try a bit more...

**Comment by qawatake** [comment]
@kabo1234 
Do you disable the legacy editor in the setting tab?
https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.3.0

**Comment by qawatake** [comment]
@kabo1234 
I release [0.3.2](https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.3.2) that supports the legacy editor.
Please try it.

**Comment by FelipeRearden** [comment]
Hello @qawatake !!!!!

I was testing the TAB command since yesterday and I think I found a BUG. 
- The TAB command is not able to navigate between ALL of the Matches
- The TAB command is not able to navigate to ANYONE of the matches.

Version 0.3.2
Obsidian 0.13.19
Legacy Mode is OFF 

Here is what I found today ....

Example 
My note name is Apple.md
my note has 3000 lines
the term I want to search is the word MacOS
I have 3 matches for this search 
The first match is located in line 2000
The second match is located in line 2500
The third is located in line 2999

Bug -> When the matches of a note are not visible when opening the MANUAL VIEW (they are in the end of the note) , the TAB command is not working.  

I think I found more bugs but I didnt find the pattern yet. I gonna keep testing to see if I found something more :)

**Comment by FelipeRearden** [comment]
> This sounds good, but I can't get it to work at all...let me try a bit more...

@kabo1234 

Try the new version 0.3.3

https://github.com/qawatake/obsidian-core-search-assistant-plugin/releases/tag/0.3.3

I think you gonna like :)

**Comment by kabo1234** [comment]
I am sorry - I still can't make this work. Maybe I am misunderstanding what manual is - if there is no preview, than how can I get to the next match? when I hit tab, it just takes me into the open note...

**Comment by qawatake** [comment]
@kabo1234 

Could you try ↓?
1. disable the **legacy editor** in the setting tab.
2. start searching. You can use any auto preview mode.
3. select an item by hitting `↓`, `↑`, `Ctrl + P`, or `Ctrl + N`.
4. open the **manual preview** by hitting `Ctrl + Space`.
5. Hit `Tab`. Then you will be able to focus a match.

**Comment by kabo1234** [comment]
> @kabo1234
> 
> Could you try ↓?
> 
> 1. disable the **legacy editor** in the setting tab.
> 2. start searching. You can use any auto preview mode.
> 3. select an item by hitting `↓`, `↑`, `Ctrl + P`, or `Ctrl + N`.
> 4. open the **manual preview** by hitting `Ctrl + Space`.
> 5. Hit `Tab`. Then you will be able to focus a match.

Finally!! Yes it's now working, thank you so much for you patience! This is great!

**Comment by qawatake** [comment]
I'm glad to know that.
Let me close this issue for now.

**Comment by zcysxy** [comment]
The `Tab` and `Shift + Tab` feature is awesome! I wonder if I can set the view to the first match automatically? Currently I need to open the preview, and then hit `Tab` to see the first match. It would be cool if it can scroll to the first match automatically without hitting an additional `Tab`.
