### ISSUE TITLE
Does not work after update to Obsidian 1.2.7

### ISSUE THREAD

**Issue by tprotopopescu** [qawatake/obsidian-core-search-assistant-plugin#62]
Just updated to Obsidian 1.2.7 and the plugin does not work any more. All that happens is the obsidian search, cards are not displayed. Tried setting manual preview changing the display option (single vs cards etc). Nothing.

**Comment by writtenfool** [comment]
You might find Obsidian Float Search https://github.com/Quorafind/Obsidian-Float-Search. I love it.

**Comment by tprotopopescu** [comment]
Thank you! Great plugin, I rely on this a lot!
