### ISSUE TITLE
[BUG] Default Split Direction not Saving the Selection

### ISSUE THREAD

**Issue by FelipeRearden** [qawatake/obsidian-core-search-assistant-plugin#8]
Hello @qawatake !!!!

I love the new setting to define the position for the new new panel :)

Just to let you know that after changing from the default option `horizontal` from `vertical` the choice is not applied when you close the setting window:

- Step 1: Open plugin settings window
- Step 2: change from horizontal to vertical
- Step 3: go to hotkeys window (or any other window from settings)
- Step 4: go back to plugin settings window

You will see that the option is horizontal instead of vertical

Version 2.0.0

Have a great day!!!!!!!

**Comment by qawatake** [comment]
@FelipeRearden 
Thank you for a feedback!
I will fix the bug in the next update.

**Comment by FelipeRearden** [comment]
Hello @qawatake  !!!!!

Working perfect on version 0.2.1 on Obsidian 0.13.19

## One Comment 

As a tester, I think it´s my duty to share with you this. 

I just notice that when using CRTL+SHIFT+ENTER the cursor/caret is not focused in the new active note . 
- after open a new note, I had to use the command FOCUS ON EDITOR to make the caret cursor appear in the note
If you replicate these steps you will see

Step 1: CRTL+SHIFT+ENTER to open in a new panel
Step 2: the new active note is the note that we open from the hotkey (100% right)
step 3: try to start typing, you will see that there is not caret cursors
Step 4: Command Palette -> Focus On Editor to make the caret appear
Step 5: start to type

Just to let you know :)

I wish you a fantastic day!!!!!

**Comment by FelipeRearden** [comment]
> I just notice that when using CRTL+SHIFT+ENTER the cursor/caret is not focused in the new active note .

From my test, version 0.3.3 solved this Issue

After hitting the 2 commands, I could get the caret position in the Active Note everytime :)
